services:
  - type: web
    name: koi-studio
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /api/cookies
    envVars:
      - key: NODE_ENV
        value: production
